import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { 
  FileText, 
  Volume2, 
  Download, 
  Share2, 
  Phone, 
  Navigation, 
  Video, 
  UserRoundCheck, 
  CheckCircle2, 
  Calendar, 
  Clock, 
  Building2, 
  Droplet, 
  Globe,
  File,
  Sparkles
} from 'lucide-react';
import { useLanguage } from '../context/LanguageContext';
import { getCurrentCase } from '../services/caseStore';
import { speak } from '../utils/voice';

export default function FinalReport() {
  const navigate = useNavigate();
  const { language, t, currentLanguageObj } = useLanguage();

  const [currentCase] = useState(() => getCurrentCase());
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [showDemoConsultModal, setShowDemoConsultModal] = useState(false);

  const patient = currentCase.patient;
  const history = currentCase.clinicalHistory;
  const hospital = currentCase.hospital || { name: 'Government General Hospital', type: 'Government General', address: 'Central Bus Stand Road', phone: '+91 40 2460 0121', distance: 2.4 };
  const doctor = currentCase.doctor || { name: 'Dr. Ananya Sharma', specialty: 'General Medicine' };
  const appointment = currentCase.appointment;

  // Formatted report text for voice speech synthesis in selected language
  const reportSummaryText = `
    MediKiosk Clinical Report Summary.
    Case ID: ${currentCase.caseId}.
    Patient Name: ${patient.name || 'Patient'}, Age: ${patient.age || '45'} Years.
    Blood Group: ${patient.bloodGroup || 'Unknown'}.
    Chief Complaint: ${history.chiefComplaint || 'Consultation'}.
    Duration: ${history.duration || 'Not specified'}.
    Hospital: ${hospital.name}.
    Doctor: ${doctor.name}, ${doctor.specialty}.
    Appointment Date: ${appointment.date}, Time: ${appointment.time}.
  `;

  // TTS Speech Output
  const handleListenReport = () => {
    if (isSpeaking) {
      window.speechSynthesis.cancel();
      setIsSpeaking(false);
      return;
    }

    setIsSpeaking(true);
    speak(reportSummaryText, language, () => setIsSpeaking(false));
  };

  // Download / Print Printable Appointment Report
  const handleDownloadReport = () => {
    const printContent = `
      ==================================================
      MEDIKIOSK CLINICAL INTAKE & APPOINTMENT SUMMARY
      ==================================================
      CASE ID: ${currentCase.caseId}
      DATE: ${new Date().toLocaleDateString()}
      --------------------------------------------------
      PATIENT INFORMATION:
      • Name: ${patient.name}
      • Age: ${patient.age} Yrs | Gender: ${patient.gender}
      • Phone: ${patient.phone}
      • Blood Group: ${patient.bloodGroup}
      • Preferred Language: ${patient.preferredLanguage}
      
      CLINICAL HISTORY & SYMPTOMS:
      • Chief Complaint: ${history.chiefComplaint}
      • Duration: ${history.duration}
      • Severity: ${history.severity}
      • Past Medical History: ${history.previousDiseases || 'None reported'}
      • Current Medications: ${history.medications || 'None'}
      • Allergies: ${history.allergies || 'No known allergies'}

      RECOMMENDED SPECIALTY:
      • Specialty: ${currentCase.careRecommendation?.recommendedSpecialty || 'General Medicine'}

      HOSPITAL & APPOINTMENT DETAILS:
      • Hospital Name: ${hospital.name} (${hospital.type})
      • Address: ${hospital.address}
      • Distance: ${hospital.distance} km away
      • Doctor: ${doctor.name} (${doctor.specialty})
      • Appointment Date: ${appointment.date}
      • Appointment Time: ${appointment.time}
      • Consultation Type: ${appointment.type === 'online' ? 'Online Video Consultation' : 'In-Person OPD Visit'}
      ==================================================
      This summary is generated by MediKiosk AI Clinical Intake.
      Please present this Case ID at the hospital desk.
    `;

    const blob = new Blob([printContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `MediKiosk_Appointment_${currentCase.caseId}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="registration-container">
      {/* Header Banner */}
      <div className="registration-header-card" style={{ background: 'linear-gradient(135deg, rgba(6,182,212,0.15), rgba(59,130,246,0.15))', border: '1px solid var(--accent-cyan)' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '1rem' }}>
          <div className="step-indicator-badge" style={{ background: 'var(--accent-emerald)', color: '#fff' }}>
            <CheckCircle2 size={16} />
            <span>Step 4 of 4: Booking & Final Report Confirmed</span>
          </div>

          <div style={{ background: 'rgba(0,0,0,0.4)', padding: '0.4rem 1rem', borderRadius: '20px', border: '1px solid var(--border-color)' }}>
            <span style={{ fontSize: '0.9rem', color: '#fff' }}>
              Case ID: <strong style={{ color: 'var(--accent-cyan)' }}>{currentCase.caseId}</strong>
            </span>
          </div>
        </div>

        <h1 className="registration-title" style={{ marginTop: '0.75rem' }}>{t('patientReportTitle')}</h1>
        <p className="registration-subtitle">
          Your clinical intake is saved and linked to Case ID <strong>{currentCase.caseId}</strong>. It is now accessible on the Doctor Workstation.
        </p>

        {/* Action Button Strip */}
        <div style={{ display: 'flex', gap: '0.75rem', flexWrap: 'wrap', marginTop: '1.25rem' }}>
          <button 
            type="button" 
            className={`btn ${isSpeaking ? 'btn-danger' : 'btn-primary'}`}
            onClick={handleListenReport}
          >
            <Volume2 size={18} />
            <span>{isSpeaking ? 'Stop Speaking' : `${t('listenReport')} (${currentLanguageObj.native})`}</span>
          </button>

          <button type="button" className="btn btn-secondary" onClick={handleDownloadReport}>
            <Download size={18} />
            <span>{t('downloadAppointment')}</span>
          </button>

          <a 
            href={`https://www.google.com/maps/dir/?api=1&destination=${hospital.lat || 17.3850},${hospital.lng || 78.4867}`}
            target="_blank" 
            rel="noreferrer"
            className="btn btn-secondary"
            style={{ textDecoration: 'none' }}
          >
            <Navigation size={18} />
            <span>{t('getDirections')}</span>
          </a>

          {hospital.phone && (
            <a href={`tel:${hospital.phone}`} className="btn btn-secondary" style={{ textDecoration: 'none' }}>
              <Phone size={18} />
              <span>{t('callHospital')}</span>
            </a>
          )}

          <button type="button" className="btn btn-secondary" onClick={() => setShowDemoConsultModal(true)}>
            <Video size={18} />
            <span>{t('consultOnline')}</span>
          </button>

          <button type="button" className="btn btn-primary" onClick={() => navigate('/doctor-dashboard')}>
            <UserRoundCheck size={18} />
            <span>{t('openDoctorDashboard')}</span>
          </button>
        </div>
      </div>

      {/* Main Report View */}
      <div className="glass-card">
        <div className="form-grid-2" style={{ borderBottom: '1px solid var(--border-color)', paddingBottom: '1.5rem', marginBottom: '1.5rem' }}>
          {/* Patient Details */}
          <div>
            <h3 style={{ color: 'var(--accent-cyan)', marginBottom: '0.75rem' }}>🧑 Patient Details</h3>
            <p><strong>Name:</strong> {patient.name || 'Ramesh Kumar'}</p>
            <p><strong>Age / Gender:</strong> {patient.age || '45'} Yrs / {patient.gender || 'Male'}</p>
            <p><strong>Phone:</strong> {patient.phone || '9876543210'}</p>
            <p><strong>Blood Group:</strong> <span className="badge badge-green">{patient.bloodGroup || 'unknown'}</span></p>
            <p><strong>Preferred Language:</strong> {patient.preferredLanguage || 'English'}</p>
          </div>

          {/* Appointment & Doctor */}
          <div>
            <h3 style={{ color: 'var(--accent-cyan)', marginBottom: '0.75rem' }}>🏥 Hospital & Doctor Appointment</h3>
            <p><strong>Hospital:</strong> {hospital.name} ({hospital.type})</p>
            <p><strong>Address:</strong> {hospital.address}</p>
            <p><strong>Distance:</strong> {hospital.distance || 2.4} km away</p>
            <p><strong>Consulting Physician:</strong> {doctor.name} ({doctor.specialty})</p>
            <p><strong>Schedule:</strong> 📅 {appointment.date} at ⏰ {appointment.time}</p>
            <p><strong>Type:</strong> <span className="badge badge-green">{appointment.type === 'online' ? 'Online Consultation' : 'In-Person OPD Visit'}</span></p>
          </div>
        </div>

        {/* Clinical Symptoms & Reports */}
        <div>
          <h3 style={{ color: 'var(--accent-cyan)', marginBottom: '0.75rem' }}>🩺 Clinical History & Uploaded Documents</h3>
          <div style={{ background: 'rgba(0,0,0,0.3)', padding: '1.25rem', borderRadius: '12px', border: '1px solid var(--border-color)', marginBottom: '1rem' }}>
            <p><strong>Chief Complaint:</strong> {history.chiefComplaint || 'General consultation'}</p>
            <p><strong>Duration:</strong> {history.duration || 'Not specified'}</p>
            <p><strong>Severity:</strong> {history.severity || 'Moderate'}</p>
            <p><strong>Past Diseases:</strong> {history.previousDiseases || 'None reported'}</p>
            <p><strong>Current Medicines:</strong> {history.medications || 'None'}</p>
            <p><strong>Known Allergies:</strong> {history.allergies || 'No known allergies'}</p>
          </div>

          {currentCase.medicalReports && currentCase.medicalReports.length > 0 && (
            <div>
              <strong>Uploaded Reports ({currentCase.medicalReports.length}):</strong>
              <ul style={{ listStyle: 'none', padding: 0, marginTop: '0.5rem' }}>
                {currentCase.medicalReports.map((rep, i) => (
                  <li key={i} style={{ background: 'rgba(255,255,255,0.05)', padding: '0.5rem 1rem', borderRadius: '6px', marginBottom: '0.35rem' }}>
                    📄 {rep.name} ({rep.size})
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      </div>

      {/* DEMO Online Video Consultation Modal */}
      {showDemoConsultModal && (
        <div className="otp-modal-backdrop" role="dialog">
          <div className="otp-modal-card" style={{ maxWidth: '550px' }}>
            <div style={{ textAlign: 'center', marginBottom: '1rem' }}>
              <Video size={48} style={{ color: 'var(--accent-cyan)' }} />
              <h3>DEMO ONLINE CONSULTATION ROOM</h3>
              <p>Connecting to {doctor.name} ({doctor.specialty})</p>
            </div>

            <div style={{ background: '#000', height: '220px', borderRadius: '12px', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--accent-emerald)', flexDirection: 'column', gap: '0.5rem' }}>
              <Sparkles size={32} />
              <span>[DEMO VIDEO ROOM: Camera & Audio Active]</span>
              <small style={{ color: 'var(--text-muted)' }}>Case ID: {currentCase.caseId}</small>
            </div>

            <div style={{ marginTop: '1.25rem', textAlign: 'right' }}>
              <button type="button" className="btn btn-danger" onClick={() => setShowDemoConsultModal(false)}>
                Close Demo Video Room
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
